version: '3.8'

services:
  # ALECS v2.0 - Remote Mode (WebSocket + SSE)
  alecs:
    build:
      context: .
      dockerfile: build/docker/Dockerfile.v2
    container_name: alecs-mcp-server
    ports:
      - '8082:8082' # WebSocket
      - '8083:8083' # SSE
    environment:
      - ALECS_MODE=remote
      - AKAMAI_EDGERC_PATH=/app/.edgerc
      - NODE_ENV=production
    volumes:
      - ~/.edgerc:/app/.edgerc:ro
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '8082']
      interval: 30s
      timeout: 10s
      retries: 3
