version: '3.8'

services:
  alecs:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    container_name: alecs-mcp-server
    ports:
      - '8080:8080' # HTTP Transport (default for web/CDN)
      - '8082:8082' # WebSocket Transport
      - '3013:3013' # SSE Transport (legacy)
    environment:
      - NODE_ENV=production
      - MCP_TRANSPORT=${MCP_TRANSPORT:-streamable-http}
      - HTTP_PORT=${HTTP_PORT:-8080}
      - HTTP_HOST=${HTTP_HOST:-0.0.0.0}
      - HTTP_PATH=${HTTP_PATH:-/mcp}
      - CORS_ENABLED=${CORS_ENABLED:-true}
      - AUTH_TYPE=${AUTH_TYPE:-none}
      - TOKEN_MASTER_KEY=${TOKEN_MASTER_KEY:-development-key}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/mcp/health']
      interval: 30s
      timeout: 10s
      retries: 3
