# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --ignore-scripts --silent

COPY . .
RUN npm run build

# Provide dummy .edgerc to allow server to start
RUN mkdir -p /root && \
    cat <<EOF > /root/.edgerc
[default]
client_secret = dummy
host = dummy.luna.akamaiapis.net
access_token = dummy
client_token = dummy
EOF

CMD ["node", "dist/index.js"]
