/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/delete/cpcode/{network}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete by CP code
         * @description Deletes content on the selected CP code for the selected `network`. In most cases, you should [invalidate](https://techdocs.akamai.com/purge-cache/reference/invalidate-cpcode) rather than delete content. Invalidation keeps each object in cache until the version on your origin server is newer. Deletion retrieves the object regardless, which can dramatically increase the load on your origin server and would prevent Akamai from serving the old content if your origin is unreachable.
         */
        post: operations["post-delete-cpcode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete/tag/{network}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete by cache tag
         * @description Deletes content on the selected set of cache tags for the selected `network`. In most cases, you should [invalidate](https://techdocs.akamai.com/purge-cache/reference/invalidate-tag) rather than delete content. Invalidation keeps each object in cache until the version on your origin server is newer. Deletion retrieves the object regardless, which can dramatically increase the load on your origin server and would prevent Akamai from serving the old content if your origin is unreachable.
         */
        post: operations["post-delete-tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete/url/{network}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete by URL or ARL
         * @description Deletes content on the selected URL or ARL  for the selected `network`.  URLs and ARLs can be submitted in the same request. In most cases, you should [invalidate](https://techdocs.akamai.com/purge-cache/reference/invalidate-url) rather than delete content. Invalidation keeps each object in cache until the version on your origin server is newer. Deletion retrieves the object regardless, which can dramatically increase the load on your origin server and would prevent Akamai from serving the old content if your origin is unreachable.
         */
        post: operations["post-delete-url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invalidate/cpcode/{network}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate by CP code
         * @description Invalidates content on the selected CP code for the selected `network`. You should consider invalidating content by default. This keeps each object in cache until the version on your origin server is newer. Deletion retrieves the object regardless, which can dramatically increase the load on your origin server and would prevent Akamai from serving the old content if your origin is unreachable.
         */
        post: operations["post-invalidate-cpcode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invalidate/tag/{network}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate by cache tag
         * @description Invalidates content on the selected set of cache tags for the selected `network`. You should consider invalidating content by default. This keeps each object in cache until the version on your origin server is newer. Deletion retrieves the object regardless, which can dramatically increase the load on your origin server and would prevent Akamai from serving the old content if your origin is unreachable.
         */
        post: operations["post-invalidate-tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invalidate/url/{network}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate by URL or ARL
         * @description Invalidates content on the selected URL or ARL for the selected `network`. You should consider invalidating content by default. This keeps each object in cache until the version on your origin server is newer. Deletion retrieves the object regardless, which can dramatically increase the load on your origin server and would prevent Akamai from serving the old content if your origin is unreachable. URLs and ARLs can be submitted in the same request.
         */
        post: operations["post-invalidate-url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "post-delete-cpcode": {
        parameters: {
            query?: {
                /**
                 * @description For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client). The Identity and Access Management API provides a [list of available account switch keys](https://techdocs.akamai.com/iam-api/reference/get-client-account-switch-keys).
                 * @example {{accountSwitchKey}}
                 */
                accountSwitchKey?: string;
            };
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "objects": [
                 *         12345,
                 *         98765
                 *       ]
                 *     } */
                "application/json": {
                    /** @description For CP code-based operations, an array of the CP codes you want to purge. */
                    objects: number[];
                };
            };
        };
        responses: {
            /** @description Successful POST of a purge request. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Request accepted",
                     *       "estimatedSeconds": 5,
                     *       "httpStatus": 201,
                     *       "purgeId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden request. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "http://fpj-test.bad-ideas2.org/",
                     *       "httpStatus": 403,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "unauthorized arl"
                     *     } */
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Too many requests. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "",
                     *       "httpStatus": 429,
                     *       "rateLimit": 300,
                     *       "rateLimitCurrentRequestSize": 5,
                     *       "rateLimitRemaining": 1,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "CPCODE Rate Limit exceeded"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "If problem persists over multiple requests, please contact Customer Care",
                     *       "httpStatus": 500,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "internal error"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    "post-delete-tag": {
        parameters: {
            query?: {
                /**
                 * @description For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client). The Identity and Access Management API provides a [list of available account switch keys](https://techdocs.akamai.com/iam-api/reference/get-client-account-switch-keys).
                 * @example {{accountSwitchKey}}
                 */
                accountSwitchKey?: string;
            };
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "objects": [
                 *         "black-friday",
                 *         "electronics",
                 *         "laptops",
                 *         "tablets"
                 *       ]
                 *     } */
                "application/json": {
                    /** @description An array of cache tag strings you want to purge. */
                    objects: string[];
                };
            };
        };
        responses: {
            /** @description Successful POST of a purge request. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Request accepted",
                     *       "estimatedSeconds": 5,
                     *       "httpStatus": 201,
                     *       "purgeId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden request. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "http://fpj-test.bad-ideas2.org/",
                     *       "httpStatus": 403,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "unauthorized arl"
                     *     } */
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Too many requests. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "",
                     *       "httpStatus": 429,
                     *       "rateLimit": 5000,
                     *       "rateLimitCurrentRequestSize": 45,
                     *       "rateLimitRemaining": 34,
                     *       "supportId": "edtp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "TAG Rate Limit exceeded"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "If problem persists over multiple requests, please contact Customer Care",
                     *       "httpStatus": 500,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "internal error"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    "post-delete-url": {
        parameters: {
            query?: {
                /**
                 * @description For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client). The Identity and Access Management API provides a [list of available account switch keys](https://techdocs.akamai.com/iam-api/reference/get-client-account-switch-keys).
                 * @example {{accountSwitchKey}}
                 */
                accountSwitchKey?: string;
            };
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "objects": [
                 *         "https://foo1.bar.com/some/path",
                 *         "http://foo2.bar.com/some/other/path"
                 *       ]
                 *     } */
                "application/json": {
                    /** @description Lists URLs or ARLs to purge. Purges content for both `http` and `https` schemes. */
                    objects: string[];
                };
            };
        };
        responses: {
            /** @description Successful POST of a purge request. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Request accepted",
                     *       "estimatedSeconds": 5,
                     *       "httpStatus": 201,
                     *       "purgeId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden request. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "http://fpj-test.bad-ideas2.org/",
                     *       "httpStatus": 403,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "unauthorized arl"
                     *     } */
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Too many requests. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "",
                     *       "httpStatus": 429,
                     *       "rateLimit": 10000,
                     *       "rateLimitCurrentRequestSize": 110,
                     *       "rateLimitRemaining": 94,
                     *       "supportId": "edup-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "URL Rate Limit exceeded"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "If problem persists over multiple requests, please contact Customer Care",
                     *       "httpStatus": 500,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "internal error"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    "post-invalidate-cpcode": {
        parameters: {
            query?: {
                /**
                 * @description For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client). The Identity and Access Management API provides a [list of available account switch keys](https://techdocs.akamai.com/iam-api/reference/get-client-account-switch-keys).
                 * @example {{accountSwitchKey}}
                 */
                accountSwitchKey?: string;
            };
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "objects": [
                 *         12345,
                 *         98765
                 *       ]
                 *     } */
                "application/json": {
                    /** @description For CP code-based operations, an array of the CP codes you want to purge. */
                    objects: number[];
                };
            };
        };
        responses: {
            /** @description Successful response. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Request accepted",
                     *       "estimatedSeconds": 5,
                     *       "httpStatus": 201,
                     *       "purgeId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Unauthorized request. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "http://fpj-test.bad-ideas2.org/",
                     *       "httpStatus": 403,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "unauthorized arl"
                     *     } */
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Too many requests. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "",
                     *       "httpStatus": 429,
                     *       "rateLimit": 300,
                     *       "rateLimitCurrentRequestSize": 5,
                     *       "rateLimitRemaining": 1,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "CPCODE Rate Limit exceeded"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "If problem persists over multiple requests, please contact Customer Care",
                     *       "httpStatus": 500,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "internal error"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    "post-invalidate-tag": {
        parameters: {
            query?: {
                /**
                 * @description For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client). The Identity and Access Management API provides a [list of available account switch keys](https://techdocs.akamai.com/iam-api/reference/get-client-account-switch-keys).
                 * @example {{accountSwitchKey}}
                 */
                accountSwitchKey?: string;
            };
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "objects": [
                 *         "black-friday",
                 *         "electronics",
                 *         "laptops",
                 *         "tablets"
                 *       ]
                 *     } */
                "application/json": {
                    /** @description An array of cache tag strings you want to purge. */
                    objects: string[];
                };
            };
        };
        responses: {
            /** @description Successful POST of a purge request. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Request accepted",
                     *       "estimatedSeconds": 5,
                     *       "httpStatus": 201,
                     *       "purgeId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden request. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "http://fpj-test.bad-ideas2.org/",
                     *       "httpStatus": 403,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "unauthorized arl"
                     *     } */
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Too many requests. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "",
                     *       "httpStatus": 429,
                     *       "rateLimit": 5000,
                     *       "rateLimitCurrentRequestSize": 45,
                     *       "rateLimitRemaining": 34,
                     *       "supportId": "edtp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "TAG Rate Limit exceeded"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "If problem persists over multiple requests, please contact Customer Care",
                     *       "httpStatus": 500,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "internal error"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    "post-invalidate-url": {
        parameters: {
            query?: {
                /**
                 * @description For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client). The Identity and Access Management API provides a [list of available account switch keys](https://techdocs.akamai.com/iam-api/reference/get-client-account-switch-keys).
                 * @example {{accountSwitchKey}}
                 */
                accountSwitchKey?: string;
            };
            header?: never;
            path: {
                /**
                 * @description __Enum__ The network on which you want to invalidate or delete content, either `staging` or the default `production` network. If omitting this optional parameter, also omit any trailing slash from the shortened URL.
                 * @example {{network}}
                 */
                network: "staging" | "production";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "objects": [
                 *         "https://foo1.bar.com/some/path",
                 *         "http://foo2.bar.com/some/other/path"
                 *       ]
                 *     } */
                "application/json": {
                    /** @description Lists URLs or ARLs to purge. Purges content for both `http` and `https` schemes. */
                    objects: string[];
                };
            };
        };
        responses: {
            /** @description Successful POST of a purge request. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Request accepted",
                     *       "estimatedSeconds": 5,
                     *       "httpStatus": 201,
                     *       "purgeId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden request. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "http://fpj-test.bad-ideas2.org/",
                     *       "httpStatus": 403,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "unauthorized arl"
                     *     } */
                    "application/problem+json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Too many requests. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "",
                     *       "httpStatus": 429,
                     *       "rateLimit": 10000,
                     *       "rateLimitCurrentRequestSize": 110,
                     *       "rateLimitRemaining": 94,
                     *       "supportId": "edup-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "URL Rate Limit exceeded"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "describedBy": "https://techdocs.akamai.com/purge-cache/reference/api-errors",
                     *       "detail": "If problem persists over multiple requests, please contact Customer Care",
                     *       "httpStatus": 500,
                     *       "supportId": "edcp-NZbXzFpHBjcJeryhw6PVgG",
                     *       "title": "internal error"
                     *     } */
                    "application/json": {
                        /** @description A URL that describes the API's error response. */
                        describedBy?: string;
                        /** @description Detailed information about the HTTP status code returned with the response. */
                        detail: string;
                        /** @description The estimated number of seconds before the purge is to complete. */
                        estimatedSeconds?: number;
                        /** @description The HTTP code that indicates the status of the request to invalidate or purge content. Successful requests yield a `201` code. */
                        httpStatus: number;
                        /** @description Unique identifier for the purge request. */
                        purgeId?: string;
                        /** @description Identifier to provide Akamai Technical Support if issues arise. */
                        supportId: string;
                        /** @description Describes the response type, for example, `Rate Limit exceeded`. */
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
