name: Docker Build Test

on:
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-containers:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        dockerfile: 
          - path: Dockerfile
            tag: latest
          - path: Dockerfile.modular
            tag: modular
          - path: Dockerfile.websocket
            tag: websocket
          - path: Dockerfile.sse
            tag: sse
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=test-${{ matrix.dockerfile.tag }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ matrix.dockerfile.path }}
        push: true
        tags: |
          ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:test-${{ matrix.dockerfile.tag }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Create container summary
      if: matrix.dockerfile.tag == 'latest'
      run: |
        echo "## Docker Test Build Complete ✅" >> $GITHUB_STEP_SUMMARY
        echo "- **Registry**: ghcr.io" >> $GITHUB_STEP_SUMMARY
        echo "- **Repository**: ${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Version**: ${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Test Tags**: test-latest, test-modular, test-websocket, test-sse" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "All Docker builds successful! Ready for production release." >> $GITHUB_STEP_SUMMARY