name: Test Docker Build

on:
  workflow_dispatch:

jobs:
  test-docker:
    name: Test Docker Build & Push
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Test Docker Hub Access
      run: |
        echo "Testing Docker Hub access..."
        docker pull hello-world
        docker tag hello-world:latest acedergren/test:latest
        docker push acedergren/test:latest || echo "Push failed - checking permissions"
        docker rmi acedergren/test:latest || true
    
    - name: Build test image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: acedergren/alecs-mcp-server-akamai:test
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: List images
      run: docker images